# aliases.py

# These are used for entity extraction and matching
program_aliases = {
    'bsce': 'BS-CE',
    'bs ce': 'BS-CE',
    'bs-ce': 'BS-CE',
    'bs-cs': 'BS-CS',
    'bs cs': 'BS-CS',
    'bscs': 'BS-CS',
    'bsee': 'BS-EE',
    'bs-ee': 'BS-EE',
    'bs ee': 'BS-EE',
    'bs-ele': 'BS-ELE',
    'bsele': 'BS-ELE',
    'bs ele': 'BS-ELE',
    'bs-it': 'BS-IT',
    'bs it': 'BS-IT',
    'bsit': 'BS-IT',
    'bs-se': 'BS-SE',
    'bsse': 'BS-SE',
    'bs se': 'BS-SE'
}

# course_aliases = {
#     'a&f': 'A&F',
#     'af': 'A&F',
#     'ai': 'Ai',
#     'ai(lab)': 'Ai(Lab)',
#     'ai lab': 'Ai(Lab)',
#     'ailab': 'Ai(Lab)',
#     'aie': 'Aie',
#     'cag': 'Cag',
#     'cc': 'Cc',
#     'ccn': 'Ccn',
#     'ccn(lab)': 'Ccn(Lab)',
#     'ccn lab': 'Ccn(Lab)',
#     'ccnlab': 'Ccn(Lab)',
#     'cn': 'Cn',
#     'cn(lab)': 'Cn(Lab)',
#     'cn lab': 'Cn(Lab)',
#     'cnlab': 'Cn(Lab)',
#     'coa': 'Coa',
#     'coa(lab)': 'Coa(Lab)',
#     'coa lab': 'Coa(Lab)',
#     'coalab': 'Coa(Lab)',
#     'coal': 'Coal',
#     'coal(lab)': 'Coal(Lab)',
#     'coal lab': 'Coal(Lab)',
#     'coallab': 'Coal(Lab)',
#     'cp': 'Cp',
#     'cp(lab)': 'Cp(Lab)',
#     'cp lab': 'Cp(Lab)',
#     'cplab': 'Cp(Lab)',
#     'dld': 'Dld',
#     'dld(lab)': 'Dld(Lab)',
#     'dld lab': 'Dld(Lab)',
#     'dldlab': 'Dld(Lab)',
#     'ds': 'Ds',
#     'ds(lab)': 'Ds(Lab)',
#     'ds lab': 'Ds(Lab)',
#     'dslab': 'Ds(Lab)',
#     'dsu': 'Dsu',
#     'ece': 'Ece',
#     'ece(lab)': 'Ece(Lab)',
#     'ece lab': 'Ece(Lab)',
#     'ecelab': 'Ece(Lab)',
#     'eco': 'Eco',
#     'ee': 'Ee',
#     'ee(lab)': 'Ee(Lab)',
#     'ee lab': 'Ee(Lab)',
#     'eelab': 'Ee(Lab)',
#     'em': 'Em',
#     'em(lab)': 'Em(Lab)',
#     'em lab': 'Em(Lab)',
#     'emlab': 'Em(Lab)',
#     'eng': 'Eng',
#     'es': 'Es',
#     'fop': 'Fop',
#     'fop(lab)': 'Fop(Lab)',
#     'fop lab': 'Fop(Lab)',
#     'foplab': 'Fop(Lab)',
#     'hci': 'Hci',
#     'hci(lab)': 'Hci(Lab)',
#     'hci lab': 'Hci(Lab)',
#     'hcilab': 'Hci(Lab)',
#     'itc': 'Itc',
#     'itc(lab)': 'Itc(Lab)',
#     'itc lab': 'Itc(Lab)',
#     'itclab': 'Itc(Lab)',
#     'la': 'La',
#     'la(lab)': 'La(Lab)',
#     'la lab': 'La(Lab)',
#     'lalab': 'La(Lab)',
#     'logic': 'Logic',
#     'logic(lab)': 'Logic(Lab)',
#     'logic lab': 'Logic(Lab)',
#     'logiclab': 'Logic(Lab)',
#     'math': 'Math',
#     'math(lab)': 'Math(Lab)',
#     'math lab': 'Math(Lab)',
#     'mathlab': 'Math(Lab)',
#     'ml': 'Ml',
#     'ml(lab)': 'Ml(Lab)',
#     'ml lab': 'Ml(Lab)',
#     'mllab': 'Ml(Lab)',
#     'net': 'Net',
#     'net(lab)': 'Net(Lab)',
#     'net lab': 'Net(Lab)',
#     'netlab': 'Net(Lab)',
#     'oop': 'Oop',
#     'oop(lab)': 'Oop(Lab)',
#     'oop lab': 'Oop(Lab)',
#     'ooplas': 'Oop(Lab)',
#     'pf': 'Pf',
#     'pf(lab)': 'Pf(Lab)',
#     'pf lab': 'Pf(Lab)',
#     'pflab': 'Pf(Lab)',
#     'progfund': 'Pf',
#     'programmingfundamentals': 'Pf',
#     'programmingfundamentalslab': 'Pf(Lab)',
#     'ps': 'Ps',
#     'ps(lab)': 'Ps(Lab)',
#     'ps lab': 'Ps(Lab)',
#     'pslab': 'Ps(Lab)',
#     'se': 'Se',
#     'se(lab)': 'Se(Lab)',
#     'se lab': 'Se(Lab)',
#     'selab': 'Se(Lab)',
#     'softeng': 'Se',
#     'softeng(lab)': 'Se(Lab)',
#     'softeng lab': 'Se(Lab)',
#     'softenglab': 'Se(Lab)',
#     'stats': 'Stats',
#     'stats(lab)': 'Stats(Lab)',
#     'stats lab': 'Stats(Lab)',
#     'statslab': 'Stats(Lab)',
#     'wt': 'Wt',
#     'wt(lab)': 'Wt(Lab)',
#     'wt lab': 'Wt(Lab)',
#     'wtlab': 'Wt(Lab)',
#     'a&f': 'A&F',
#     'af': 'A&F',
#     'ai': 'Ai',
#     'ai(lab)': 'Ai(Lab)',
#     'ai lab': 'Ai(Lab)',
#     'ailab': 'Ai(Lab)',
#     'aie': 'Aie',
#     'cag': 'Cag',
#     'cc': 'Cc',
#     'ccn': 'Ccn',
#     'ccn(lab)': 'Ccn(Lab)',
#     'ccn lab': 'Ccn(Lab)',
#     'ccnlab': 'Ccn(Lab)',
#     'cn': 'Cn',
#     'cn(lab)': 'Cn(Lab)',
#     'cn lab': 'Cn(Lab)',
#     'cnlab': 'Cn(Lab)',
#     'coa': 'Coa',
#     'coa(lab)': 'Coa(Lab)',
#     'coa lab': 'Coa(Lab)',
#     'coalab': 'Coa(Lab)',
#     'coal': 'Coal',
#     'coal(lab)': 'Coal(Lab)',
#     'coal lab': 'Coal(Lab)',
#     'coallab': 'Coal(Lab)',
#     'cp': 'Cp',
#     'cp(lab)': 'Cp(Lab)',
#     'cp lab': 'Cp(Lab)',
#     'cplab': 'Cp(Lab)',
#     'dld': 'Dld',
#     'dld(lab)': 'Dld(Lab)',
#     'dld lab': 'Dld(Lab)',
#     'dldlab': 'Dld(Lab)',
#     'ds': 'Ds',
#     'ds(lab)': 'Ds(Lab)',
#     'ds lab': 'Ds(Lab)',
#     'dslab': 'Ds(Lab)',
#     'dsu': 'Dsu',
#     'ece': 'Ece',
#     'ece(lab)': 'Ece(Lab)',
#     'ece lab': 'Ece(Lab)',
#     'ecelab': 'Ece(Lab)',
#     'eco': 'Eco',
#     'ee': 'Ee',
#     'ee(lab)': 'Ee(Lab)',
#     'ee lab': 'Ee(Lab)',
#     'eelab': 'Ee(Lab)',
#     'em': 'Em',
#     'em(lab)': 'Em(Lab)',
#     'em lab': 'Em(Lab)',
#     'emlab': 'Em(Lab)',
#     'eng': 'Eng',
#     'es': 'Es',
#     'fop': 'Fop',
#     'fop(lab)': 'Fop(Lab)',
#     'fop lab': 'Fop(Lab)',
#     'foplab': 'Fop(Lab)',
#     'hci': 'Hci',
#     'hci(lab)': 'Hci(Lab)',
#     'hci lab': 'Hci(Lab)',
#     'hcilab': 'Hci(Lab)',
#     'itc': 'Itc',
#     'itc(lab)': 'Itc(Lab)',
#     'itc lab': 'Itc(Lab)',
#     'itclab': 'Itc(Lab)',
#     'la': 'La',
#     'la(lab)': 'La(Lab)',
#     'la lab': 'La(Lab)',
#     'lalab': 'La(Lab)',
#     'logic': 'Logic',
#     'logic(lab)': 'Logic(Lab)',
#     'logic lab': 'Logic(Lab)',
#     'logiclab': 'Logic(Lab)',
#     'math': 'Math',
#     'math(lab)': 'Math(Lab)',
#     'math lab': 'Math(Lab)',
#     'mathlab': 'Math(Lab)',
#     'ml': 'Ml',
#     'ml(lab)': 'Ml(Lab)',
#     'ml lab': 'Ml(Lab)',
#     'mllab': 'Ml(Lab)',
#     'net': 'Net',
#     'net(lab)': 'Net(Lab)',
#     'net lab': 'Net(Lab)',
#     'netlab': 'Net(Lab)',
#     'oop': 'Oop',
#     'oop(lab)': 'Oop(Lab)',
#     'oop lab': 'Oop(Lab)',
#     'ooplas': 'Oop(Lab)',
#     'pf': 'Pf',
#     'pf(lab)': 'Pf(Lab)',
#     'pf lab': 'Pf(Lab)',
#     'pflab': 'Pf(Lab)',
#     'progfund': 'Pf',
#     'programmingfundamentals': 'Pf',
#     'programmingfundamentalslab': 'Pf(Lab)',
#     'ps': 'Ps',
#     'ps(lab)': 'Ps(Lab)',
#     'ps lab': 'Ps(Lab)',
#     'pslab': 'Ps(Lab)',
#     'se': 'Se',
#     'se(lab)': 'Se(Lab)',
#     'se lab': 'Se(Lab)',
#     'selab': 'Se(Lab)',
#     'softeng': 'Se',
#     'softeng(lab)': 'Se(Lab)',
#     'softeng lab': 'Se(Lab)',
#     'softenglab': 'Se(Lab)',
#     'stats': 'Stats',
#     'stats(lab)': 'Stats(Lab)',
#     'stats lab': 'Stats(Lab)',
#     'statslab': 'Stats(Lab)',
#     'wt': 'Wt',
#     'wt(lab)': 'Wt(Lab)',
#     'wt lab': 'Wt(Lab)',
#     'wtlab': 'Wt(Lab)'
# }
# course_aliases = {
#     'a&f': 'A&F', 'af': 'A&F',
#     'ai': 'Ai', 'ai(lab)': 'Ai(Lab)', 'ai lab': 'Ai(Lab)', 'ailab': 'Ai(Lab)',
#     'aie': 'Aie',
#     'cag': 'Cag',
#     'cc': 'Cc',
#     'ccn': 'Ccn', 'ccn(lab)': 'Ccn(Lab)', 'ccn lab': 'Ccn(Lab)', 'ccnlab': 'Ccn(Lab)',
#     'cn': 'Cn', 'cn(lab)': 'Cn(Lab)', 'cn lab': 'Cn(Lab)', 'cnlab': 'Cn(Lab)',
#     'coa': 'Coa', 'coa(lab)': 'Coa(Lab)', 'coa lab': 'Coa(Lab)', 'coalab': 'Coa(Lab)',
#     'coal': 'Coal', 'coal(lab)': 'Coal(Lab)', 'coal lab': 'Coal(Lab)', 'coallab': 'Coal(Lab)',
#     'cp': 'Cp', 'cp(lab)': 'Cp(Lab)', 'cp lab': 'Cp(Lab)', 'cplab': 'Cp(Lab)',
#     'dld': 'Dld', 'dld(lab)': 'Dld(Lab)', 'dld lab': 'Dld(Lab)', 'dldlab': 'Dld(Lab)',
#     'ds': 'Ds', 'ds(lab)': 'Ds(Lab)', 'ds lab': 'Ds(Lab)', 'dslab': 'Ds(Lab)',
#     'dsu': 'Dsu',
#     'ece': 'Ece', 'ece(lab)': 'Ece(Lab)', 'ece lab': 'Ece(Lab)', 'ecelab': 'Ece(Lab)',
#     'eco': 'Eco',
#     'ee': 'Ee', 'ee(lab)': 'Ee(Lab)', 'ee lab': 'Ee(Lab)', 'eelab': 'Ee(Lab)',
#     'em': 'Em', 'em(lab)': 'Em(Lab)', 'em lab': 'Em(Lab)', 'emlab': 'Em(Lab)',
#     'eng': 'Eng',
#     'es': 'Es',
#     'fop': 'Fop', 'fop(lab)': 'Fop(Lab)', 'fop lab': 'Fop(Lab)', 'foplab': 'Fop(Lab)',
#     'hci': 'Hci', 'hci(lab)': 'Hci(Lab)', 'hci lab': 'Hci(Lab)', 'hcilab': 'Hci(Lab)',
#     'itc': 'Itc', 'itc(lab)': 'Itc(Lab)', 'itc lab': 'Itc(Lab)', 'itclab': 'Itc(Lab)',
#     'la': 'La', 'la(lab)': 'La(Lab)', 'la lab': 'La(Lab)', 'lalab': 'La(Lab)',
#     'logic': 'Logic', 'logic(lab)': 'Logic(Lab)', 'logic lab': 'Logic(Lab)', 'logiclab': 'Logic(Lab)',
#     'math': 'Math', 'math(lab)': 'Math(Lab)', 'math lab': 'Math(Lab)', 'mathlab': 'Math(Lab)',
#     'ml': 'Ml', 'ml(lab)': 'Ml(Lab)', 'ml lab': 'Ml(Lab)', 'mllab': 'Ml(Lab)',
#     'net': 'Net', 'net(lab)': 'Net(Lab)', 'net lab': 'Net(Lab)', 'netlab': 'Net(Lab)',
#     'oop': 'Oop', 'oop(lab)': 'Oop(Lab)', 'oop lab': 'Oop(Lab)', 'ooplas': 'Oop(Lab)',
#     'pf': 'Pf', 'pf(lab)': 'Pf(Lab)', 'pf lab': 'Pf(Lab)', 'pflab': 'Pf(Lab)',
#     'progfund': 'Pf', 'programmingfundamentals': 'Pf', 'programmingfundamentalslab': 'Pf(Lab)',
#     'ps': 'Ps', 'ps(lab)': 'Ps(Lab)', 'ps lab': 'Ps(Lab)', 'pslab': 'Ps(Lab)',
#     'se': 'Se', 'se(lab)': 'Se(Lab)', 'se lab': 'Se(Lab)', 'selab': 'Se(Lab)',
#     'softeng': 'Se', 'softeng(lab)': 'Se(Lab)', 'softeng lab': 'Se(Lab)', 'softenglab': 'Se(Lab)',
#     'stats': 'Stats', 'stats(lab)': 'Stats(Lab)', 'stats lab': 'Stats(Lab)', 'statslab': 'Stats(Lab)',
#     'wt': 'Wt', 'wt(lab)': 'Wt(Lab)', 'wt lab': 'Wt(Lab)', 'wtlab': 'Wt(Lab)'
# }
course_aliases = {
    'a&f': 'A&F', 'af': 'A&F',
    'ai': 'Ai', 'ai(lab)': 'Ai(Lab)', 'ai lab': 'Ai(Lab)', 'ailab': 'Ai(Lab)',
    'aie': 'Aie',
    'cag': 'Cag',
    'cc': 'Cc',
    'ccn': 'Ccn', 'ccn(lab)': 'Ccn(Lab)', 'ccn lab': 'Ccn(Lab)', 'ccnlab': 'Ccn(Lab)',
    'cn': 'Cn', 'cn(lab)': 'Cn(Lab)', 'cn lab': 'Cn(Lab)', 'cnlab': 'Cn(Lab)',
    'coa': 'Coa', 'coa(lab)': 'Coa(Lab)', 'coa lab': 'Coa(Lab)', 'coalab': 'Coa(Lab)',
    'coal': 'Coal', 'coal(lab)': 'Coal(Lab)', 'coal lab': 'Coal(Lab)', 'coallab': 'Coal(Lab)',
    'cp': 'Cp', 'cp(lab)': 'Cp(Lab)', 'cp lab': 'Cp(Lab)', 'cplab': 'Cp(Lab)',
    'dld': 'Dld', 'dld(lab)': 'Dld(Lab)', 'dld lab': 'Dld(Lab)', 'dldlab': 'Dld(Lab)',
    'ds': 'Ds', 'ds(lab)': 'Ds(Lab)', 'ds lab': 'Ds(Lab)', 'dslab': 'Ds(Lab)',
    'dsu': 'Dsu',
    'ece': 'Ece', 'ece(lab)': 'Ece(Lab)', 'ece lab': 'Ece(Lab)', 'ecelab': 'Ece(Lab)',
    'eco': 'Eco',
    'ee': 'Ee', 'ee(lab)': 'Ee(Lab)', 'ee lab': 'Ee(Lab)', 'eelab': 'Ee(Lab)',
    'em': 'Em', 'em(lab)': 'Em(Lab)', 'em lab': 'Em(Lab)', 'emlab': 'Em(Lab)',
    'eng': 'Eng',
    'es': 'Es',
    'fop': 'Fop', 'fop(lab)': 'Fop(Lab)', 'fop lab': 'Fop(Lab)', 'foplab': 'Fop(Lab)',
    'hci': 'Hci', 'hci(lab)': 'Hci(Lab)', 'hci lab': 'Hci(Lab)', 'hcilab': 'Hci(Lab)',
    'itc': 'Itc', 'itc(lab)': 'Itc(Lab)', 'itc lab': 'Itc(Lab)', 'itclab': 'Itc(Lab)',
    'la': 'La', 'la(lab)': 'La(Lab)', 'la lab': 'La(Lab)', 'lalab': 'La(Lab)',
    'logic': 'Logic', 'logic(lab)': 'Logic(Lab)', 'logic lab': 'Logic(Lab)', 'logiclab': 'Logic(Lab)',
    'math': 'Math', 'math(lab)': 'Math(Lab)', 'math lab': 'Math(Lab)', 'mathlab': 'Math(Lab)',
    'ml': 'Ml', 'ml(lab)': 'Ml(Lab)', 'ml lab': 'Ml(Lab)', 'mllab': 'Ml(Lab)',
    'net': 'Net', 'net(lab)': 'Net(Lab)', 'net lab': 'Net(Lab)', 'netlab': 'Net(Lab)',
    'oop': 'Oop', 'oop(lab)': 'Oop(Lab)', 'oop lab': 'Oop(Lab)', 'ooplas': 'Oop(Lab)',
    'pf': 'Pf', 'pf(lab)': 'Pf(Lab)', 'pf lab': 'Pf(Lab)', 'pflab': 'Pf(Lab)',
    'progfund': 'Pf', 'programmingfundamentals': 'Pf', 'programmingfundamentalslab': 'Pf(Lab)',
    'ps': 'Ps', 'ps(lab)': 'Ps(Lab)', 'ps lab': 'Ps(Lab)', 'pslab': 'Ps(Lab)',
    'se': 'Se', 'se(lab)': 'Se(Lab)', 'se lab': 'Se(Lab)', 'selab': 'Se(Lab)',
    'softeng': 'Se', 'softeng(lab)': 'Se(Lab)', 'softeng lab': 'Se(Lab)', 'softenglab': 'Se(Lab)',
    'stats': 'Stats', 'stats(lab)': 'Stats(Lab)', 'stats lab': 'Stats(Lab)', 'statslab': 'Stats(Lab)',
    'wt': 'Wt', 'wt(lab)': 'Wt(Lab)', 'wt lab': 'Wt(Lab)', 'wtlab': 'Wt(Lab)'
}
